package fr.vlik.grandfantasia.loader.equip;

import java.util.HashMap;

import fr.vlik.grandfantasia.enums.Language;
import fr.vlik.grandfantasia.enums.Quality;
import fr.vlik.grandfantasia.enums.TypeEffect;
import fr.vlik.grandfantasia.enums.TypeStaticEffect;
import fr.vlik.grandfantasia.equip.Ring;
import fr.vlik.grandfantasia.stats.Calculable;
import fr.vlik.grandfantasia.stats.Effect;
import fr.vlik.grandfantasia.stats.Proc;
import fr.vlik.grandfantasia.stats.Proc.Activation;
import fr.vlik.grandfantasia.stats.Proc.TDB;
import fr.vlik.grandfantasia.stats.RegenEffect;
import fr.vlik.grandfantasia.stats.RegenEffect.TypeRegen;
import fr.vlik.grandfantasia.stats.StaticEffect;
import fr.vlik.grandfantasia.stats.Effect.Target;

@SuppressWarnings("serial")
public class LoaderRing {
	
	public static Ring[] getRing() {
		return new Ring[] {
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Tyrannie sacrée de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "tdb0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.FCE, false, 31, true),
					new Effect(TypeEffect.VIT, false, 27, true),
					new Effect(TypeEffect.VOL, false, 18, true),
					new Effect(TypeEffect.Glace, false, 32),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.Toucher, false, 30),
						new Effect(TypeEffect.DegPSacre, false, 2400),
						new StaticEffect(TypeStaticEffect.x3Skill, 15),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Assertion sacrée de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.FCE, false, 31, true),
					new Effect(TypeEffect.VIT, false, 27, true),
					new Effect(TypeEffect.VOL, false, 18, true),
					new Effect(TypeEffect.Feu, false, 32),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 6),
						new Effect(TypeEffect.DCCP, false, 9),
						new Effect(TypeEffect.Atk, true, 9),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Cycle de Roue de la fortune de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.VIT, false, 29, true),
					new Effect(TypeEffect.INT, false, 28, true),
					new Effect(TypeEffect.VOL, false, 20, true),
					new Effect(TypeEffect.Ombre, false, 32),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.AtkM, true, 9),
						new Effect(TypeEffect.VitComp, false, 6),
						new StaticEffect(TypeStaticEffect.x3Skill, 15),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Fugacité de Roue de la fortune de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.VIT, false, 29, true),
					new Effect(TypeEffect.INT, false, 28, true),
					new Effect(TypeEffect.VOL, false, 20, true),
					new Effect(TypeEffect.Sacre, false, 32),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 15),
						new Effect(TypeEffect.DCCM, false, 39),
						new Effect(TypeEffect.VitComp, false, 3),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Fin de mort de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.FCE, false, 27, true),
					new Effect(TypeEffect.VIT, false, 31, true),
					new Effect(TypeEffect.INT, false, 18, true),
					new Effect(TypeEffect.Foudre, false, 32),
					new Proc(15, Activation.Attacked, 7, new Calculable[] {
						new Effect(TypeEffect.DefP, true, 12),
						new Effect(TypeEffect.DefM, true, 12),
						new Effect(TypeEffect.RTCCP, false, 9),
						new Effect(TypeEffect.RTCCM, false, 9),
						new Effect(TypeEffect.Depla, false, 7),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Méfaits de mort de Tarot ténébreux"); put(Language.EN, ""); }},
				100, Quality.GOLD, true, "-1", true, "100tarot", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 664, true),
					new Effect(TypeEffect.FCE, false, 27, true),
					new Effect(TypeEffect.VIT, false, 31, true),
					new Effect(TypeEffect.INT, false, 18, true),
					new Effect(TypeEffect.Nature, false, 32),
					new Proc(15, Activation.Attacked, 7, new Calculable[] {
						new Effect(TypeEffect.MEN, false, 1200),
						new Effect(TypeEffect.ReducP, true, 9),
						new Effect(TypeEffect.ReducM, true, 9),
						new Effect(TypeEffect.DegPOmbre, false, 900),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Force infinie de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "gt2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.FCE, false, 28, true),
					new Effect(TypeEffect.VIT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 16, true),
					new Effect(TypeEffect.Glace, false, 30),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 8),
						new StaticEffect(TypeStaticEffect.x2STD, 20),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Force débordante de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "tdb9", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.FCE, false, 28, true),
					new Effect(TypeEffect.VIT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 16, true),
					new Effect(TypeEffect.Feu, false, 30),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 8),
						new Effect(TypeEffect.VitAtk, false, 8),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Zodiaque visionnaire de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "gt3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.VIT, false, 26, true),
					new Effect(TypeEffect.INT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 18, true),
					new Effect(TypeEffect.Ombre, false, 30),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.AtkM, true, 12),
						new StaticEffect(TypeStaticEffect.x2Skill, 25),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Zodiaque méprisant de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "gt0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.VIT, false, 26, true),
					new Effect(TypeEffect.INT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 18, true),
					new Effect(TypeEffect.Sacre, false, 30),
					new Proc(15, Activation.Attack, 6, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 8),
						new Effect(TypeEffect.VitComp, false, 8),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Lune féérique de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "gt1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.FCE, false, 25, true),
					new Effect(TypeEffect.VIT, false, 28, true),
					new Effect(TypeEffect.INT, false, 16, true),
					new Effect(TypeEffect.Foudre, false, 30),
					new Proc(15, Activation.Attacked, 5, new Calculable[] {
						new Effect(TypeEffect.DefP, true, 12),
						new Effect(TypeEffect.DefM, true, 12),
						new Effect(TypeEffect.Depla, false, 4),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Lune enchantée de Tarot ténébreux"); put(Language.EN, ""); }},
				95, Quality.GOLD, true, "-1", true, "tdb6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 641, true),
					new Effect(TypeEffect.FCE, false, 25, true),
					new Effect(TypeEffect.VIT, false, 28, true),
					new Effect(TypeEffect.INT, false, 16, true),
					new Effect(TypeEffect.Nature, false, 30),
					new Proc(15, Activation.Attacked, 5, new Calculable[] {
						new Effect(TypeEffect.MEN, false, 16),
						new Effect(TypeEffect.ReducP, true, 16),
						new Effect(TypeEffect.ReducM, true, 16),
					}),
				}, null),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Gladiateur"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb0", false, "tdb0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.FCE, false, 26, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.Feu, false, 30),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -700, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 20, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -3000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Dragon"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb1", false, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.FCE, false, 21, true),
					new Effect(TypeEffect.AGI, false, 25, true),
					new Effect(TypeEffect.Foudre, false, 30),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -700, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, -50, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -1000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de Foi Divine"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb2", false, "tdb2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.INT, false, 23, true),
					new Effect(TypeEffect.VOL, false, 23, true),
					new Effect(TypeEffect.Glace, false, 30),
					new Proc(10, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.ReloadComp, false, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -1000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Squelette"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb3", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.INT, false, 26, true),
					new Effect(TypeEffect.VOL, false, 20, true),
					new Effect(TypeEffect.Nature, false, 30),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, -1, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, 500, TypeRegen.REGENERATION),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Écusson de Puissance"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb4", false, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 669, true),
					new Effect(TypeEffect.FCE, false, 15, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Ombre, false, 30),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.Depla, false, -1, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -2000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Œil pourpre"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb0", false, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.FCE, false, 28, true),
					new Effect(TypeEffect.VIT, false, 22, true),
					new Effect(TypeEffect.Feu, false, 20),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.FCE, true, 1),
					}),
					new Proc(Activation.Attack, 20, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.DegAtkAll, false, 3000),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Œil d'émeraude"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb1", false, "tdb6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.FCE, false, 23, true),
					new Effect(TypeEffect.AGI, false, 27, true),
					new Effect(TypeEffect.Foudre, false, 20),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.AGI, true, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, 15),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bénédiction des Anciens"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb2", false, "tdb7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.INT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 25, true),
					new Effect(TypeEffect.Glace, false, 20),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.VIT, true, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.Shield, false, 5000),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "​Malédiction du Hasard"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb3", false, "tdb8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.INT, false, 28, true),
					new Effect(TypeEffect.VOL, false, 22, true),
					new Effect(TypeEffect.Nature, false, 20),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.Toucher, false, -1, Target.OPPONENT),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new StaticEffect(TypeStaticEffect.Poisse, 20, Target.OPPONENT),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bravoure du Champion"); put(Language.EN, ""); }},
				90, Quality.GOLD, false, "tdb4", false, "tdb9", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 669, true),
					new Effect(TypeEffect.FCE, false, 17, true),
					new Effect(TypeEffect.INT, false, 17, true),
					new Effect(TypeEffect.AGI, false, 17, true),
					new Effect(TypeEffect.Ombre, false, 25),
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.DefP, true, -1, Target.OPPONENT),
						new Effect(TypeEffect.DefM, true, -1, Target.OPPONENT),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.ReducP, false, -10, Target.OPPONENT),
						new Effect(TypeEffect.ReducM, false, -10, Target.OPPONENT),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de Fureur Incontrôlable"); put(Language.EN, ""); }},
				78, Quality.GOLD, true, "-1", true, "messager0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 561, true),
					new Effect(TypeEffect.FCE, false, 21, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.AGI, false, 14, true),
					new Effect(TypeEffect.DCCP, false, 2),
					new Effect(TypeEffect.Foudre, false, 27),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'Infinie Sagesse"); put(Language.EN, ""); }},
				78, Quality.GOLD, true, "-1", true, "tdb8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 561, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.VOL, false, 20, true),
					new Effect(TypeEffect.DCCM, false, 2),
					new Effect(TypeEffect.Nature, false, 27),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Rugissant de Rastar"); put(Language.EN, ""); }},
				68, Quality.GOLD, true, "-1", true, "messager1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 511, true),
					new Effect(TypeEffect.FCE, false, 18, true),
					new Effect(TypeEffect.VIT, false, 15, true),
					new Effect(TypeEffect.AGI, false, 12, true),
					new Effect(TypeEffect.TCCP, false, 2),
					new Effect(TypeEffect.Glace, false, 25),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Silencieux de Kraato"); put(Language.EN, ""); }},
				68, Quality.GOLD, true, "-1", true, "tdb0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 511, true),
					new Effect(TypeEffect.VIT, false, 15, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.VOL, false, 17, true),
					new Effect(TypeEffect.TCCM, false, 2),
					new Effect(TypeEffect.Feu, false, 25),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Pierre de Libération de Rastar"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.FCE, false, 12, true),
					new Effect(TypeEffect.VIT, false, 13, true),
					new Effect(TypeEffect.AGI, false, 10, true),
					new Effect(TypeEffect.Glace, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Rosaire du Repentir de Kraato"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.FCE, false, 14, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Feu, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne de Pénitence d'Envie"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Ombre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Emeraude de l'Eveil de Paresse"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.FCE, false, 10, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.AGI, false, 10, true),
					new Effect(TypeEffect.Sacre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague du Pardon de Raze"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.FCE, false, 12, true),
					new Effect(TypeEffect.INT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 13, true),
					new Effect(TypeEffect.Foudre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Marque de Purification d'Apride"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "messager7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.AGI, false, 12, true),
					new Effect(TypeEffect.Nature, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague de Flora la Douce"); put(Language.EN, ""); }},
				58, Quality.GOLD, true, "-1", true, "flora", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 460, true),
					new Effect(TypeEffect.FCE, false, 5, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.INT, false, 5, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.AGI, false, 5, true),
					new Effect(TypeEffect.Nature, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de la Tyrannie"); put(Language.EN, ""); }},
				100, Quality.ORANGE, false, "-1", true, "tdb9", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 588, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.Feu, false, 18),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 12),
						new Effect(TypeEffect.DegP, false, 6),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de la Tourmente"); put(Language.EN, ""); }},
				100, Quality.ORANGE, false, "-1", true, "gt0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 588, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.Feu, false, 18),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 12),
						new Effect(TypeEffect.DegM, false, 6),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de l'Enfer"); put(Language.EN, ""); }},
				100, Quality.ORANGE, false, "-1", true, "tdb6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 605, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.PV, false, 950),
					new Effect(TypeEffect.Ombre, false, 18),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 10),
						new Effect(TypeEffect.DegM, false, 10),
						new Effect(TypeEffect.Toucher, false, 15),
						new Effect(TypeEffect.ESQ, false, 15),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Violence"); put(Language.EN, ""); }},
				95, Quality.ORANGE, false, "-1", true, "gt1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 559, true),
					new Effect(TypeEffect.VIT, false, 18, true),
					new Effect(TypeEffect.VOL, false, 9, true),
					new Effect(TypeEffect.PV, false, 800),
					new Effect(TypeEffect.Ombre, false, 17),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 10),
						new Effect(TypeEffect.DegM, false, 10),
						new Effect(TypeEffect.Toucher, false, 10),
						new Effect(TypeEffect.ESQ, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Gladiateur "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb0", false, "tdb0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.FCE, false, 26, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.Feu, false, 30),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Dragon "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb1", false, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.FCE, false, 21, true),
					new Effect(TypeEffect.AGI, false, 25, true),
					new Effect(TypeEffect.Foudre, false, 30),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Foi divine "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb2", false, "tdb2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.INT, false, 23, true),
					new Effect(TypeEffect.VOL, false, 23, true),
					new Effect(TypeEffect.Glace, false, 30),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Squelette "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb3", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 584, true),
					new Effect(TypeEffect.INT, false, 26, true),
					new Effect(TypeEffect.VOL, false, 20, true),
					new Effect(TypeEffect.Nature, false, 30),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Écusson de Puissance "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb4", false, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 669, true),
					new Effect(TypeEffect.FCE, false, 15, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Ombre, false, 25),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Œil pourpre "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb0", false, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.FCE, false, 28, true),
					new Effect(TypeEffect.VIT, false, 22, true),
					new Effect(TypeEffect.Feu, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Œil d'émeraude "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb1", false, "tdb6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.FCE, false, 23, true),
					new Effect(TypeEffect.AGI, false, 27, true),
					new Effect(TypeEffect.Foudre, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bénédiction des Anciens "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb2", false, "tdb7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.INT, false, 25, true),
					new Effect(TypeEffect.VOL, false, 25, true),
					new Effect(TypeEffect.Glace, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Malédiction du Hasard "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb3", false, "tdb8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 630, true),
					new Effect(TypeEffect.INT, false, 28, true),
					new Effect(TypeEffect.VOL, false, 22, true),
					new Effect(TypeEffect.Nature, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bravoure du Champion "); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "tdb4", false, "tdb9", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 669, true),
					new Effect(TypeEffect.FCE, false, 17, true),
					new Effect(TypeEffect.INT, false, 17, true),
					new Effect(TypeEffect.AGI, false, 17, true),
					new Effect(TypeEffect.Ombre, false, 25),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de Désintégration"); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "-1", true, "gt2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 541, true),
					new Effect(TypeEffect.VIT, false, 18, true),
					new Effect(TypeEffect.VOL, false, 9, true),
					new Effect(TypeEffect.Feu, false, 17),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 12),
						new Effect(TypeEffect.DegP, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative des Trois Royaumes"); put(Language.EN, ""); }},
				90, Quality.ORANGE, false, "-1", true, "gt3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 541, true),
					new Effect(TypeEffect.VIT, false, 18, true),
					new Effect(TypeEffect.VOL, false, 9, true),
					new Effect(TypeEffect.Feu, false, 17),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 12),
						new Effect(TypeEffect.DegM, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Destruction"); put(Language.EN, ""); }},
				85, Quality.ORANGE, false, "-1", true, "gt4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 510, true),
					new Effect(TypeEffect.VIT, false, 16, true),
					new Effect(TypeEffect.VOL, false, 8, true),
					new Effect(TypeEffect.PV, false, 650),
					new Effect(TypeEffect.Ombre, false, 16),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 8),
						new Effect(TypeEffect.DegM, false, 8),
						new Effect(TypeEffect.Toucher, false, 10),
						new Effect(TypeEffect.ESQ, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de la Vengeance"); put(Language.EN, ""); }},
				80, Quality.ORANGE, false, "-1", true, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 489, true),
					new Effect(TypeEffect.VIT, false, 16, true),
					new Effect(TypeEffect.VOL, false, 8, true),
					new Effect(TypeEffect.Ombre, false, 16),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 10),
						new Effect(TypeEffect.DegP, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de l'Apathie"); put(Language.EN, ""); }},
				80, Quality.ORANGE, false, "-1", true, "gt5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 489, true),
					new Effect(TypeEffect.VIT, false, 16, true),
					new Effect(TypeEffect.VOL, false, 8, true),
					new Effect(TypeEffect.Glace, false, 16),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 10),
						new Effect(TypeEffect.DegM, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite du Jugement"); put(Language.EN, ""); }},
				75, Quality.ORANGE, false, "-1", true, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 468, true),
					new Effect(TypeEffect.VIT, false, 14, true),
					new Effect(TypeEffect.VOL, false, 7, true),
					new Effect(TypeEffect.PV, false, 500),
					new Effect(TypeEffect.Ombre, false, 15),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 8),
						new Effect(TypeEffect.DegM, false, 8),
						new Effect(TypeEffect.Toucher, false, 5),
						new Effect(TypeEffect.ESQ, false, 5),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de la Tyrannie"); put(Language.EN, ""); }},
				70, Quality.ORANGE, false, "-1", true, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 447, true),
					new Effect(TypeEffect.VIT, false, 14, true),
					new Effect(TypeEffect.VOL, false, 7, true),
					new Effect(TypeEffect.Feu, false, 15),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de la Compassion"); put(Language.EN, ""); }},
				70, Quality.ORANGE, false, "-1", true, "gt6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 447, true),
					new Effect(TypeEffect.VIT, false, 14, true),
					new Effect(TypeEffect.VOL, false, 7, true),
					new Effect(TypeEffect.Nature, false, 15),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Domination"); put(Language.EN, ""); }},
				65, Quality.ORANGE, false, "-1", true, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 425, true),
					new Effect(TypeEffect.VIT, false, 12, true),
					new Effect(TypeEffect.VOL, false, 6, true),
					new Effect(TypeEffect.Ombre, false, 14),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 8),
						new Effect(TypeEffect.DegM, false, 8),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale du Trouble"); put(Language.EN, ""); }},
				60, Quality.ORANGE, false, "-1", true, "gt5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 403, true),
					new Effect(TypeEffect.VIT, false, 12, true),
					new Effect(TypeEffect.VOL, false, 6, true),
					new Effect(TypeEffect.Foudre, false, 14),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 8),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de la Soumission"); put(Language.EN, ""); }},
				60, Quality.ORANGE, false, "-1", true, "gt7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 403, true),
					new Effect(TypeEffect.VIT, false, 12, true),
					new Effect(TypeEffect.VOL, false, 6, true),
					new Effect(TypeEffect.Sacre, false, 14),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 8),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Revanche"); put(Language.EN, ""); }},
				55, Quality.ORANGE, false, "-1", true, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 380, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 5, true),
					new Effect(TypeEffect.Ombre, false, 13),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 6),
						new Effect(TypeEffect.DegM, false, 6),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale des Vagues"); put(Language.EN, ""); }},
				50, Quality.ORANGE, false, "-1", true, "gt6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 356, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 5, true),
					new Effect(TypeEffect.Glace, false, 13),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 6),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de l'Obscurité"); put(Language.EN, ""); }},
				50, Quality.ORANGE, false, "-1", true, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 356, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.VOL, false, 5, true),
					new Effect(TypeEffect.Ombre, false, 13),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 6),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Cruauté"); put(Language.EN, ""); }},
				45, Quality.ORANGE, false, "-1", true, "gt7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.VIT, false, 8, true),
					new Effect(TypeEffect.VOL, false, 4, true),
					new Effect(TypeEffect.Ombre, false, 12),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 4),
						new Effect(TypeEffect.DegM, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale du Tremblement"); put(Language.EN, ""); }},
				40, Quality.ORANGE, false, "-1", true, "gt7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 306, true),
					new Effect(TypeEffect.VIT, false, 8, true),
					new Effect(TypeEffect.VOL, false, 4, true),
					new Effect(TypeEffect.Nature, false, 12),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative du Confinement"); put(Language.EN, ""); }},
				40, Quality.ORANGE, false, "-1", true, "gt8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 306, true),
					new Effect(TypeEffect.VIT, false, 8, true),
					new Effect(TypeEffect.VOL, false, 4, true),
					new Effect(TypeEffect.Feu, false, 12),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 4),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Élite de la Détermination"); put(Language.EN, ""); }},
				35, Quality.ORANGE, false, "-1", true, "gt5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 280, true),
					new Effect(TypeEffect.VIT, false, 6, true),
					new Effect(TypeEffect.VOL, false, 3, true),
					new Effect(TypeEffect.Ombre, false, 11),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DegP, false, 2),
						new Effect(TypeEffect.DegM, false, 2),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Martiale de Frappe"); put(Language.EN, ""); }},
				30, Quality.ORANGE, false, "-1", true, "gt4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 251, true),
					new Effect(TypeEffect.VIT, false, 6, true),
					new Effect(TypeEffect.VOL, false, 3, true),
					new Effect(TypeEffect.Nature, false, 11),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCP, false, 2),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chevalière Méditative de Protection"); put(Language.EN, ""); }},
				30, Quality.ORANGE, false, "-1", true, "gt6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 251, true),
					new Effect(TypeEffect.VIT, false, 6, true),
					new Effect(TypeEffect.VOL, false, 3, true),
					new Effect(TypeEffect.Nature, false, 11),
					new Proc(15, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.TCCM, false, 2),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Damné du Diablotin"); put(Language.EN, ""); }},
				100, Quality.BLUE, false, "-1", true, "sombre0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 612, true),
					new Effect(TypeEffect.VIT, false, 24, true),
					new Effect(TypeEffect.VOL, false, 14, true),
					new Effect(TypeEffect.Ombre, false, 24),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier scintillant lunesang"); put(Language.EN, ""); }},
				90, Quality.BLUE, false, "90sombre", true, "sombre6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 574, true),
					new Effect(TypeEffect.FCE, false, 12, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier d'ombre lunesang"); put(Language.EN, ""); }},
				90, Quality.BLUE, false, "90sombre", true, "sombre15", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 574, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.INT, false, 12, true),
					new Effect(TypeEffect.AGI, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier de l'Âme Noire"); put(Language.EN, ""); }},
				90, Quality.BLUE, false, "-1", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 585, true),
					new Effect(TypeEffect.VIT, false, 20, true),
					new Effect(TypeEffect.Ombre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'argent de lune brillante"); put(Language.EN, ""); }},
				89, Quality.BLUE, false, "-1", false, "89bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 569, true),
					new Effect(TypeEffect.FCE, false, 17, true),
					new Effect(TypeEffect.INT, false, 17, true),
					new Effect(TypeEffect.AGI, false, 17, true),
					new Effect(TypeEffect.Ombre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Précepteur des Jours Saints"); put(Language.EN, ""); }},
				89, Quality.BLUE, false, "-1", false, "sombre10", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 569, true),
					new Effect(TypeEffect.FCE, false, 17, true),
					new Effect(TypeEffect.AGI, false, 17, true),
					new Effect(TypeEffect.Glace, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier de Cristal Translucide"); put(Language.EN, ""); }},
				89, Quality.BLUE, false, "-1", false, "sombre13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 569, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.INT, false, 17, true),
					new Effect(TypeEffect.Feu, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Fantôme Esclave"); put(Language.EN, ""); }},
				89, Quality.BLUE, false, "-1", false, "89bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 569, true),
					new Effect(TypeEffect.FCE, false, 17, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.Foudre, false, 22),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne de Mithril"); put(Language.EN, ""); }},
				83, Quality.BLUE, false, "-1", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 543, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.VOL, false, 15, true),
					new Effect(TypeEffect.Nature, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Bûcher"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb10", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -700, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 20, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -3000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de la Foudre"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb11", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -700, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, -50, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -1000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Vent"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb12", new Calculable[] {
					new Proc(10, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.ReloadComp, false, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -1000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Démoniste"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb13", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, -1, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, 500, TypeRegen.REGENERATION),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Blizzard"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb14", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.Depla, false, -1, Target.OPPONENT),
						new RegenEffect(TypeEffect.PV, false, -500, TypeRegen.POISON),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, -2000, TypeRegen.POISON),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de concentration"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "gt6", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.FCE, true, 1),
					}),
					new Proc(Activation.Attack, 20, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.DegAtkAll, false, 3000),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'accélération"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb15", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.AGI, true, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.VitAtk, false, 15),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'écu en acier"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "gt7", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.VIT, true, 1),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.Shield, false, 5000),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau des arts interdits"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "gt8", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.Toucher, false, -1, Target.OPPONENT),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new StaticEffect(TypeStaticEffect.Poisse, 20, Target.OPPONENT),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'érosion d'armure"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", false, "tdb16", new Calculable[] {
					new Proc(100, Activation.Attack, 3, new Calculable[] {
						new Effect(TypeEffect.DefP, true, -1, Target.OPPONENT),
						new Effect(TypeEffect.DefM, true, -1, Target.OPPONENT),
					}),
					new Proc(Activation.Attack, 10, TDB.TDB, new Calculable[] {
						new Effect(TypeEffect.ReducP, false, -10, Target.OPPONENT),
						new Effect(TypeEffect.ReducM, false, -10, Target.OPPONENT),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier du chasseur de la bête divine"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "80sombre", true, "sombre2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.FCE, false, 12, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier Yakari de la bête divine"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "80sombre", true, "sombre3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.INT, false, 12, true),
					new Effect(TypeEffect.AGI, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague du Garde Aguerri"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", true, "tdb4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.FCE, false, 18, true),
					new Effect(TypeEffect.VIT, false, 12, true),
					new Effect(TypeEffect.Feu, false, 21),
					new Effect(TypeEffect.Depla, false, 3),
					new Effect(TypeEffect.VitAtk, false, 3),
					new Proc(10, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.ReducStd, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague de Mornelune"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", true, "tdb5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.FCE, false, 13, true),
					new Effect(TypeEffect.AGI, false, 17, true),
					new Effect(TypeEffect.Foudre, false, 21),
					new Effect(TypeEffect.DegP, false, 5),
					new Proc(10, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.Depla, false, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague d'Os Réptilienne"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", true, "tdb1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.VOL, false, 15, true),
					new Effect(TypeEffect.Glace, false, 21),
					new Effect(TypeEffect.DegM, false, 5),
					new Proc(10, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.VitComp, false, 15),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Démoniste Sombre"); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", true, "gt8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 530, true),
					new Effect(TypeEffect.INT, false, 18, true),
					new Effect(TypeEffect.VOL, false, 12, true),
					new Effect(TypeEffect.Nature, false, 21),
					new Effect(TypeEffect.ReducP, false, 5),
					new Effect(TypeEffect.ReducM, false, 5),
					new Proc(10, Activation.Attack, 8, new Calculable[] {
						new RegenEffect(TypeEffect.PV, false, 250, TypeRegen.REGENERATION, 2),
						new RegenEffect(TypeEffect.PM, false, 250, TypeRegen.REGENERATION, 2),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Démoniste Sombre "); put(Language.EN, ""); }},
				80, Quality.BLUE, false, "-1", true, "sombre1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 535, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne de l'Esprit Scellé"); put(Language.EN, ""); }},
				78, Quality.BLUE, false, "-1", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 521, true),
					new Effect(TypeEffect.FCE, false, 15, true),
					new Effect(TypeEffect.VIT, false, 15, true),
					new Effect(TypeEffect.Foudre, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de Sang Polaire"); put(Language.EN, ""); }},
				77, Quality.BLUE, false, "-1", false, "sombre10", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 512, true),
					new Effect(TypeEffect.VIT, false, 15, true),
					new Effect(TypeEffect.INT, false, 15, true),
					new Effect(TypeEffect.Feu, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Courage des Terres Polaires"); put(Language.EN, ""); }},
				76, Quality.BLUE, false, "-1", false, "sombre6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 512, true),
					new Effect(TypeEffect.FCE, false, 15, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Glace, false, 21),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Artefact de Bengale"); put(Language.EN, ""); }},
				72, Quality.BLUE, false, "-1", false, "72bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 494, true),
					new Effect(TypeEffect.VIT, false, 13, true),
					new Effect(TypeEffect.AGI, false, 13, true),
					new Effect(TypeEffect.Feu, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Coupe d'Ivoire des Glaces"); put(Language.EN, ""); }},
				72, Quality.BLUE, false, "-1", false, "72bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 494, true),
					new Effect(TypeEffect.VIT, false, 13, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.Glace, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Montre silencieuse lumicloche"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "70sombre", true, "sombre4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.FCE, false, 10, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Montre statique lumicloche"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "70sombre", true, "sombre5", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.INT, false, 10, true),
					new Effect(TypeEffect.AGI, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Peurécarlate"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", true, "tdb10", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.FCE, false, 16, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.Feu, false, 20),
					new Effect(TypeEffect.DegP, false, 3),
					new Proc(8, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.DefP, true, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Jadérable"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", true, "gvg0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.FCE, false, 11, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Foudre, false, 20),
					new Effect(TypeEffect.TCCP, false, 5),
					new Proc(8, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.VitAtk, true, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de Minuit"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", true, "gvg1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.VOL, false, 13, true),
					new Effect(TypeEffect.Glace, false, 20),
					new Effect(TypeEffect.IntComp, false, 30),
					new Proc(8, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.ReducM, false, 3),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau Rose de Nacre"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", true, "tdb15", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.INT, false, 16, true),
					new Effect(TypeEffect.VOL, false, 10, true),
					new Effect(TypeEffect.Nature, false, 20),
					new RegenEffect(TypeEffect.PM, false, 30, TypeRegen.REGENERATION, 5),
					new Proc(8, Activation.Attack, 8, new Calculable[] {
						new Effect(TypeEffect.VitAtk, true, 10),
					}),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Pendentif Lunaire de Sprite Sombre"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", false, "sombre6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.VOL, false, 9, true),
					new Effect(TypeEffect.Ombre, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Perle tombée du Ciel"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", false, "70bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.FCE, false, 13, true),
					new Effect(TypeEffect.AGI, false, 13, true),
					new Effect(TypeEffect.Foudre, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Améthyste Ensorcerlée"); put(Language.EN, ""); }},
				70, Quality.BLUE, false, "-1", false, "70bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 484, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.VOL, false, 13, true),
					new Effect(TypeEffect.Nature, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bracelet des Glaces Éternelles"); put(Language.EN, ""); }},
				68, Quality.BLUE, false, "-1", false, "sombre6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 475, true),
					new Effect(TypeEffect.FCE, false, 13, true),
					new Effect(TypeEffect.VIT, false, 13, true),
					new Effect(TypeEffect.Feu, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de Cristal Ancestral"); put(Language.EN, ""); }},
				68, Quality.BLUE, false, "-1", false, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 475, true),
					new Effect(TypeEffect.AGI, false, 26, true),
					new Effect(TypeEffect.Glace, false, 20),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague Condutrice d'Inspiration"); put(Language.EN, ""); }},
				62, Quality.BLUE, false, "-1", false, "tdb14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 446, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.VOL, false, 9, true),
					new Effect(TypeEffect.Glace, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Noyau de Cristallisation du Dragon de Feu"); put(Language.EN, ""); }},
				62, Quality.BLUE, false, "-1", false, "62bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 446, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.AGI, false, 11, true),
					new Effect(TypeEffect.Feu, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Colonne de Glace de Mille Ans"); put(Language.EN, ""); }},
				62, Quality.BLUE, false, "-1", false, "62bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 446, true),
					new Effect(TypeEffect.INT, false, 8, true),
					new Effect(TypeEffect.VOL, false, 14, true),
					new Effect(TypeEffect.Glace, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Fierté de l'Artisan Légendaire"); put(Language.EN, ""); }},
				62, Quality.BLUE, false, "-1", false, "62bleu2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 446, true),
					new Effect(TypeEffect.FCE, false, 13, true),
					new Effect(TypeEffect.AGI, false, 9, true),
					new Effect(TypeEffect.Foudre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'or de la lignée interdite"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "60sombre", true, "sombre7", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.FCE, false, 8, true),
					new Effect(TypeEffect.INT, false, 7, true),
					new Effect(TypeEffect.VOL, false, 7, true),
					new Effect(TypeEffect.Ombre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'argent de la lignée interdite"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "60sombre", true, "sombre8", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.VIT, false, 7, true),
					new Effect(TypeEffect.INT, false, 8, true),
					new Effect(TypeEffect.AGI, false, 7, true),
					new Effect(TypeEffect.Ombre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Pierre au Sceau Feu de l'Enfer"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "60bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.FCE, false, 14, true),
					new Effect(TypeEffect.AGI, false, 8, true),
					new Effect(TypeEffect.Feu, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Pierre du Sceau Gelé"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "messager2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Glace, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Réserve d'Énergie"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "60bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.VIT, false, 15, true),
					new Effect(TypeEffect.AGI, false, 7, true),
					new Effect(TypeEffect.Foudre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Champignon à Parfum Floral"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "60bleu2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.VIT, false, 10, true),
					new Effect(TypeEffect.INT, false, 12, true),
					new Effect(TypeEffect.Nature, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Oeil de l'Enfer Déchu"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "sombre9", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.VIT, false, 17, true),
					new Effect(TypeEffect.Ombre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Prière Silencieuse de l'Exorciste"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "tdb13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.VIT, false, 9, true),
					new Effect(TypeEffect.INT, false, 13, true),
					new Effect(TypeEffect.Foudre, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague de la Foi à toute épreuve"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.FCE, false, 11, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.Nature, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Perles Protectrices du Vent Divin"); put(Language.EN, ""); }},
				60, Quality.BLUE, false, "-1", false, "sombre13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 436, true),
					new Effect(TypeEffect.FCE, false, 7, true),
					new Effect(TypeEffect.AGI, false, 15, true),
					new Effect(TypeEffect.Feu, false, 19),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Rugissement des Morts"); put(Language.EN, ""); }},
				52, Quality.BLUE, false, "-1", false, "tdb13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 396, true),
					new Effect(TypeEffect.FCE, false, 6, true),
					new Effect(TypeEffect.INT, false, 12, true),
					new Effect(TypeEffect.Foudre, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Détermination Totale"); put(Language.EN, ""); }},
				52, Quality.BLUE, false, "-1", false, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 396, true),
					new Effect(TypeEffect.VOL, false, 14, true),
					new Effect(TypeEffect.Nature, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Déesse de la Compassion"); put(Language.EN, ""); }},
				52, Quality.BLUE, false, "-1", false, "sombre13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 396, true),
					new Effect(TypeEffect.FCE, false, 9, true),
					new Effect(TypeEffect.VIT, false, 9, true),
					new Effect(TypeEffect.Feu, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Contrôleur d'Esprit"); put(Language.EN, ""); }},
				52, Quality.BLUE, false, "-1", false, "tdb14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 396, true),
					new Effect(TypeEffect.AGI, false, 14, true),
					new Effect(TypeEffect.Glace, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de gemmes de l'étranger"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "50sombre", true, "sombre10", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.FCE, false, 7, true),
					new Effect(TypeEffect.INT, false, 6, true),
					new Effect(TypeEffect.VOL, false, 6, true),
					new Effect(TypeEffect.Ombre, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de cristal de l'étranger"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "50sombre", true, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.VIT, false, 6, true),
					new Effect(TypeEffect.INT, false, 7, true),
					new Effect(TypeEffect.AGI, false, 6, true),
					new Effect(TypeEffect.Ombre, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Fossile Coeur du Diable Ardent de collection"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "-1", false, "50bleu", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.AGI, false, 14, true),
					new Effect(TypeEffect.Nature, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Tabou du maître minéral"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "-1", false, "sombre1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.FCE, false, 14, true),
					new Effect(TypeEffect.Feu, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Médaillon du Maître de l'Herbe"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "-1", false, "sombre6", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.INT, false, 14, true),
					new Effect(TypeEffect.Glace, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier du Dieu de la Mort Dure"); put(Language.EN, ""); }},
				50, Quality.BLUE, false, "-1", false, "sombre12", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 386, true),
					new Effect(TypeEffect.VIT, false, 14, true),
					new Effect(TypeEffect.Ombre, false, 18),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Nucléus du Feu de l'Enfer"); put(Language.EN, ""); }},
				44, Quality.BLUE, false, "-1", false, "62bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 354, true),
					new Effect(TypeEffect.INT, false, 5, true),
					new Effect(TypeEffect.AGI, false, 9, true),
					new Effect(TypeEffect.Feu, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Coeur de Glace Polaire"); put(Language.EN, ""); }},
				44, Quality.BLUE, false, "-1", false, "62bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 354, true),
					new Effect(TypeEffect.FCE, false, 8, true),
					new Effect(TypeEffect.VOL, false, 6, true),
					new Effect(TypeEffect.Glace, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Appareil de Mouvement Perpétuel"); put(Language.EN, ""); }},
				44, Quality.BLUE, false, "-1", false, "62bleu2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 354, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.Foudre, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Corne d'Ivoire"); put(Language.EN, ""); }},
				44, Quality.BLUE, false, "-1", false, "72bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 354, true),
					new Effect(TypeEffect.VOL, false, 11, true),
					new Effect(TypeEffect.Nature, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Mystérieux collier de dissimulation"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "40sombre", true, "sombre13", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.FCE, false, 6, true),
					new Effect(TypeEffect.INT, false, 5, true),
					new Effect(TypeEffect.VOL, false, 5, true),
					new Effect(TypeEffect.Ombre, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Mystérieux collier de discrétion"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "40sombre", true, "sombre14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.VIT, false, 5, true),
					new Effect(TypeEffect.INT, false, 6, true),
					new Effect(TypeEffect.AGI, false, 5, true),
					new Effect(TypeEffect.Ombre, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague du Forgeron"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "-1", false, "40bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.FCE, false, 11, true),
					new Effect(TypeEffect.Feu, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Perles médicinales exquises"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "-1", false, "sombre14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.INT, false, 11, true),
					new Effect(TypeEffect.Glace, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Emeraude des profondeurs maritimes de collection"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "-1", false, "40bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.AGI, false, 11, true),
					new Effect(TypeEffect.Nature, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier de l'Esprit Sombre"); put(Language.EN, ""); }},
				40, Quality.BLUE, false, "-1", false, "tdb3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 332, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.Ombre, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Ordre Runique Ancestral"); put(Language.EN, ""); }},
				36, Quality.BLUE, false, "-1", false, "messager1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 309, true),
					new Effect(TypeEffect.VIT, false, 11, true),
					new Effect(TypeEffect.Nature, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Epingle du Dieu Lunaire"); put(Language.EN, ""); }},
				36, Quality.BLUE, false, "-1", false, "messager4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 309, true),
					new Effect(TypeEffect.FCE, false, 7, true),
					new Effect(TypeEffect.INT, false, 7, true),
					new Effect(TypeEffect.Feu, false, 17),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Marque de vitesse anneau ombremort"); put(Language.EN, ""); }},
				30, Quality.BLUE, false, "-1", false, "gvg1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 272, true),
					new Effect(TypeEffect.FCE, false, 4, true),
					new Effect(TypeEffect.INT, false, 3, true),
					new Effect(TypeEffect.VOL, false, 3, true),
					new Effect(TypeEffect.Ombre, false, 16),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Marque de vitesse anneau d'ombre"); put(Language.EN, ""); }},
				30, Quality.BLUE, false, "-1", false, "tdb14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 272, true),
					new Effect(TypeEffect.VIT, false, 3, true),
					new Effect(TypeEffect.INT, false, 4, true),
					new Effect(TypeEffect.AGI, false, 3, true),
					new Effect(TypeEffect.Ombre, false, 16),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Volonté du Martyr"); put(Language.EN, ""); }},
				28, Quality.BLUE, false, "-1", false, "28bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 260, true),
					new Effect(TypeEffect.INT, false, 5, true),
					new Effect(TypeEffect.VOL, false, 5, true),
					new Effect(TypeEffect.PV, false, 240),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bénédiction de la Fée"); put(Language.EN, ""); }},
				28, Quality.BLUE, false, "-1", false, "28bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 260, true),
					new Effect(TypeEffect.AGI, false, 8, true),
					new Effect(TypeEffect.PM, false, 120),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague à Gemme Rouge"); put(Language.EN, ""); }},
				45, Quality.GREEN, false, "-1", false, "sombre10", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 304, true),
					new Effect(TypeEffect.INT, false, 4, true),
					new Effect(TypeEffect.PV, false, 320),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier de Combat"); put(Language.EN, ""); }},
				40, Quality.GREEN, false, "-1", false, "sombre14", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 281, true),
					new Effect(TypeEffect.FCE, false, 4, true),
					new Effect(TypeEffect.Feu, false, 10),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague de Concentration du Pouvoir Magique"); put(Language.EN, ""); }},
				40, Quality.GREEN, false, "-1", false, "tdb12", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 281, true),
					new Effect(TypeEffect.INT, false, 4, true),
					new Effect(TypeEffect.Glace, false, 10),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne d'Orbe du Fort"); put(Language.EN, ""); }},
				31, Quality.GREEN, false, "-1", false, "28bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 236, true),
					new Effect(TypeEffect.VOL, false, 3, true),
					new Effect(TypeEffect.Foudre, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague de Lumière Magique"); put(Language.EN, ""); }},
				31, Quality.GREEN, false, "-1", false, "40bleu0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 236, true),
					new Effect(TypeEffect.INT, false, 3, true),
					new Effect(TypeEffect.Nature, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Avertissement des Frères de la Pierre Ferreuse"); put(Language.EN, ""); }},
				30, Quality.GREEN, false, "-1", false, "sombre11", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 230, true),
					new Effect(TypeEffect.FCE, false, 3, true),
					new Effect(TypeEffect.Feu, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Collier d'adepte de la sorcellerie"); put(Language.EN, ""); }},
				30, Quality.GREEN, false, "-1", false, "28bleu1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 230, true),
					new Effect(TypeEffect.INT, false, 3, true),
					new Effect(TypeEffect.Glace, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Idole du Diable géant de collection"); put(Language.EN, ""); }},
				30, Quality.GREEN, false, "-1", false, "30vert", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 230, true),
					new Effect(TypeEffect.AGI, false, 3, true),
					new Effect(TypeEffect.Nature, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau de l'Esprit du Pouvoir Magique"); put(Language.EN, ""); }},
				30, Quality.GREEN, false, "-1", false, "sombre1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 230, true),
					new Effect(TypeEffect.VIT, false, 3, true),
					new Effect(TypeEffect.Ombre, false, 9),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne de la Dent Ensanglantée"); put(Language.EN, ""); }},
				25, Quality.GREEN, false, "-1", false, "messager3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 184, true),
					new Effect(TypeEffect.AGI, false, 2, true),
					new Effect(TypeEffect.PV, false, 160),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague Verte"); put(Language.EN, ""); }},
				25, Quality.GREEN, false, "-1", false, "messager1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 184, true),
					new Effect(TypeEffect.VOL, false, 2, true),
					new Effect(TypeEffect.PM, false, 80),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Pouvoir du Géant"); put(Language.EN, ""); }},
				20, Quality.GREEN, false, "-1", false, "20vert", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 173, true),
					new Effect(TypeEffect.FCE, false, 2, true),
					new Effect(TypeEffect.PV, false, 160),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Défense de Mammouth Sacré"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "90blanc0", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.PV, false, 720),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Boucles d'Oreille de l'Ombre Lunaire"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "messager4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.PM, false, 360),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau d'Or du Sang du Démon"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "tdb15", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.PV, false, 360),
					new Effect(TypeEffect.Feu, false, 7),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Clé du Coffre Glacé"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "90blanc1", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.PM, false, 180),
					new Effect(TypeEffect.Glace, false, 7),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Torche du Géant du Temple"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "90blanc2", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.Feu, false, 13),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Feuille Glacée de l'Arbre Ingelable"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "90blanc3", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.Glace, false, 13),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Cendres du Dieu du Tonnerre"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "90blanc4", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.Foudre, false, 13),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Anneau du Sourire de la Nymphe"); put(Language.EN, ""); }},
				90, Quality.WHITE, false, "-1", false, "flora", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 441, true),
					new Effect(TypeEffect.Nature, false, 13),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Chaîne du Courage"); put(Language.EN, ""); }},
				10, Quality.WHITE, false, "-1", false, "20vert", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 84, true),
					new Effect(TypeEffect.PV, false, 80),
				}, null ),
			new Ring(new HashMap<Language, String>() {{ put(Language.FR, "Bague du Pouvoir Magique"); put(Language.EN, ""); }},
				10, Quality.WHITE, false, "-1", false, "10blanc", new Calculable[] {
					new Effect(TypeEffect.DefM, false, 84, true),
					new Effect(TypeEffect.PM, false, 40),
				}, null ),
		};
	}
}
