package fr.vlik.grandfantasia.loader.customEquip;

import java.util.HashMap;

import fr.vlik.grandfantasia.charac.Grade.GradeName;
import fr.vlik.grandfantasia.customEquip.CustomArmor;
import fr.vlik.grandfantasia.enums.Language;
import fr.vlik.grandfantasia.enums.TypeEffect;
import fr.vlik.grandfantasia.equip.Armor.ArmorType;
import fr.vlik.grandfantasia.loader.equip.LoaderGauntlet;
import fr.vlik.grandfantasia.stats.Calculable;
import fr.vlik.grandfantasia.stats.Effect;

@SuppressWarnings("serial")
class LoaderCustomGauntlet {
	
	static CustomArmor[] getGauntlet() {
		CustomArmor[] class1 = getGuerrier();
		CustomArmor[] class2 = getArcher();
		CustomArmor[] class3 = getPretre();
		CustomArmor[] class4 = getMage();
		CustomArmor[] class5 = getMeca();
		CustomArmor[] class6 = getVoyageur();
		
		CustomArmor[] result = new CustomArmor[class1.length + class2.length + class3.length + class4.length + class5.length + class6.length];
		
		int i = 0;
		for(; i < class1.length; i++) {
			result[i] = class1[i];
		}

		for(int j = 0; j < class2.length; i++, j++) {
			result[i] = class2[j];
		}

		for(int j = 0; j < class3.length; i++, j++) {
			result[i] = class3[j];
		}
		
		for(int j = 0; j < class4.length; i++, j++) {
			result[i] = class4[j];
		}

		for(int j = 0; j < class5.length; i++, j++) {
			result[i] = class5[j];
		}
		
		for(int j = 0; j < class6.length; i++, j++) {
			result[i] = class6[j];
		}
		
		return result;
	}
	
	private static CustomArmor[] getGuerrier() {
		return new CustomArmor[] {
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Tyranniques"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80nucleus0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 376, true),
					new Effect(TypeEffect.DefM, false, 280, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCP, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Chant Éolien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 384, true),
					new Effect(TypeEffect.DefM, false, 274, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Gladiateur Barbare"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 376, true),
					new Effect(TypeEffect.DefM, false, 280, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCP, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Chant Éolien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 384, true),
					new Effect(TypeEffect.DefM, false, 274, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Feu de Météore"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 364, true),
					new Effect(TypeEffect.DefM, false, 269, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCP, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Précipice"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 371, true),
					new Effect(TypeEffect.DefM, false, 264, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Feu Solaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 364, true),
					new Effect(TypeEffect.DefM, false, 269, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCP, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Couchant"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 371, true),
					new Effect(TypeEffect.DefM, false, 264, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protèges-poignet de la Baleine Blanche"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 357, true),
					new Effect(TypeEffect.DefM, false, 263, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.TCCP, false, 1.6),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protèges-poignet du Grand Pèlerin"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 364, true),
					new Effect(TypeEffect.DefM, false, 258, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.DCCP, false, 11),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Sentinelle des Enfers"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 354, true),
					new Effect(TypeEffect.DefM, false, 261, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Gardien du Sanctuaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 361, true),
					new Effect(TypeEffect.DefM, false, 256, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Danger des Plaines"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 345, true),
					new Effect(TypeEffect.DefM, false, 253, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.TCCP, false, 1.4),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Troubadour de la Justice"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 352, true),
					new Effect(TypeEffect.DefM, false, 248, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.DCCP, false, 9),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants d'Orgueil"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 342, true),
					new Effect(TypeEffect.DefM, false, 251, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Silence Sacré"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 349, true),
					new Effect(TypeEffect.DefM, false, 246, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Féroce Destructeur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 332, true),
					new Effect(TypeEffect.DefM, false, 243, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.TCCP, false, 1.2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants d'Exorcisation"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 339, true),
					new Effect(TypeEffect.DefM, false, 238, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.DCCP, false, 7),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Étoile de Feu"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 330, true),
					new Effect(TypeEffect.DefM, false, 241, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Jade Pourpre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 337, true),
					new Effect(TypeEffect.DefM, false, 236, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Sacrificateur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 319, true),
					new Effect(TypeEffect.DefM, false, 232, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCP, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Éblouissement Guerrier"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 325, true),
					new Effect(TypeEffect.DefM, false, 227, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Carnage"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 317, true),
					new Effect(TypeEffect.DefM, false, 230, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de la Hargne Sauvage"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 323, true),
					new Effect(TypeEffect.DefM, false, 226, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Barbares"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 306, true),
					new Effect(TypeEffect.DefM, false, 222, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCP, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets d'Améthyste"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 312, true),
					new Effect(TypeEffect.DefM, false, 218, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Fourrés"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 304, true),
					new Effect(TypeEffect.DefM, false, 220, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Articulés"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 310, true),
					new Effect(TypeEffect.DefM, false, 216, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de la Bête du Grondement du Feu"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "95pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 293, true),
					new Effect(TypeEffect.DefM, false, 211, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Défenseur de la Loi de l'Eglise"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 299, true),
					new Effect(TypeEffect.DefM, false, 207, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-mains de l'Intrépide"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "95pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 290, true),
					new Effect(TypeEffect.DefM, false, 209, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Bras du Glorieux Chevalier"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 296, true),
					new Effect(TypeEffect.DefM, false, 205, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Être Démoniaque"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 280, true),
					new Effect(TypeEffect.DefM, false, 201, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Coudes du Héros"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 288, true),
					new Effect(TypeEffect.DefM, false, 201, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Mains d'Os et de Sang"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 260, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Samouraï"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 267, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Main Armée de la Carcasse de la Bête"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 260, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Supérieurs"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 267, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Meneur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 237, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Coudes du Chevalier Gardien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 244, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-mains du Dictateur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 237, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Bras du Chevalier Prétorien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pvp6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 244, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Bataille Ancestrale"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pvp6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 213, true),
					new Effect(TypeEffect.DefM, false, 151, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Défenseur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 219, true),
					new Effect(TypeEffect.DefM, false, 151, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Champ de Bataille Ancestral"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pvp6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 213, true),
					new Effect(TypeEffect.DefM, false, 151, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Défenseur Tenace"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.PALADIN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 219, true),
					new Effect(TypeEffect.DefM, false, 151, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Commandant"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 187, true),
					new Effect(TypeEffect.DefM, false, 133, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Commandant de l'Avant- Poste"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 187, true),
					new Effect(TypeEffect.DefM, false, 133, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de l'Avant-Garde"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 159, true),
					new Effect(TypeEffect.DefM, false, 113, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de Bataille Courageuse"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 159, true),
					new Effect(TypeEffect.DefM, false, 113, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets d'Élite"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				15, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 136, true),
					new Effect(TypeEffect.DefM, false, 96, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines Éclatantes"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.BERSERKER, GradeName.PALADIN, },
				9, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53bleu1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 110, true),
					new Effect(TypeEffect.DefM, false, 78, true),
				}),
		};
	}
	
	private static CustomArmor[] getArcher() {
		return new CustomArmor[] {
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Coucher de Lune"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "65pve2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 320, true),
					new Effect(TypeEffect.DefM, false, 305, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 20),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Coquille"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 313, true),
					new Effect(TypeEffect.DefM, false, 311, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCP, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Promeneur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 320, true),
					new Effect(TypeEffect.DefM, false, 305, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 20),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Bourreau"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25vert0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 313, true),
					new Effect(TypeEffect.DefM, false, 311, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCP, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Araignée Fantôme"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 309, true),
					new Effect(TypeEffect.DefM, false, 293, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 18),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Ombre Sereine"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "65pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 303, true),
					new Effect(TypeEffect.DefM, false, 299, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCP, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Étoile Filante"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "90gold2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 309, true),
					new Effect(TypeEffect.DefM, false, 293, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 18),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Nocturnes"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 303, true),
					new Effect(TypeEffect.DefM, false, 299, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCP, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Montagne Chantante"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 303, true),
					new Effect(TypeEffect.DefM, false, 287, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.DCCP, false, 16),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Traître Assassin"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 297, true),
					new Effect(TypeEffect.DefM, false, 293, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.TCCP, false, 1.6),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Archer Sauvage"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 301, true),
					new Effect(TypeEffect.DefM, false, 284, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Garde Silencieux"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 295, true),
					new Effect(TypeEffect.DefM, false, 290, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Ombre d'Argent"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 293, true),
					new Effect(TypeEffect.DefM, false, 275, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.DCCP, false, 14),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Lame Furtive"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 287, true),
					new Effect(TypeEffect.DefM, false, 281, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.TCCP, false, 1.4),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Pêcheur de Nuages"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 291, true),
					new Effect(TypeEffect.DefM, false, 273, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Serpent d'Émeraude"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 285, true),
					new Effect(TypeEffect.DefM, false, 279, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Horizon Lointain"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 283, true),
					new Effect(TypeEffect.DefM, false, 265, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.DCCP, false, 12),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Mirage Ninja"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 277, true),
					new Effect(TypeEffect.DefM, false, 270, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.TCCP, false, 1.2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Faucon d'Or"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 281, true),
					new Effect(TypeEffect.DefM, false, 262, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Ninja de l'Ombre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 275, true),
					new Effect(TypeEffect.DefM, false, 267, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Tempêtes Polaires"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 271, true),
					new Effect(TypeEffect.DefM, false, 253, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Guerrier Lunaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 266, true),
					new Effect(TypeEffect.DefM, false, 258, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCP, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Œil de Faucon"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 269, true),
					new Effect(TypeEffect.DefM, false, 251, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Seigneur de l'Ombre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 264, true),
					new Effect(TypeEffect.DefM, false, 256, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Confortables de Nomade"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 260, true),
					new Effect(TypeEffect.DefM, false, 241, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Griffes de Turquoise"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 255, true),
					new Effect(TypeEffect.DefM, false, 246, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCP, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de Chasse"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 258, true),
					new Effect(TypeEffect.DefM, false, 239, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Griffes Carmines"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 253, true),
					new Effect(TypeEffect.DefM, false, 244, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Promeneur du Vent"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 249, true),
					new Effect(TypeEffect.DefM, false, 230, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Assassin Spectral"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "65pve2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 244, true),
					new Effect(TypeEffect.DefM, false, 235, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Tireur à l'Arme Lourde"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 247, true),
					new Effect(TypeEffect.DefM, false, 227, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Serpent Venimeux"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "65pve2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 242, true),
					new Effect(TypeEffect.DefM, false, 232, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines Célestes"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 240, true),
					new Effect(TypeEffect.DefM, false, 223, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Fantôme Diabolique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 233, true),
					new Effect(TypeEffect.DefM, false, 223, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Coudes Météore"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 223, true),
					new Effect(TypeEffect.DefM, false, 206, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Bracelet de la Volonté de Vivre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 217, true),
					new Effect(TypeEffect.DefM, false, 206, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Bras de la Comète"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 223, true),
					new Effect(TypeEffect.DefM, false, 206, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets des Directions Fatales"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 217, true),
					new Effect(TypeEffect.DefM, false, 206, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Bracelet de l'Hymne"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 203, true),
					new Effect(TypeEffect.DefM, false, 187, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de l'Officier des Affaires Spéciales"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25vert0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 198, true),
					new Effect(TypeEffect.DefM, false, 187, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines de la Dérive"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 203, true),
					new Effect(TypeEffect.DefM, false, 187, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Tueur au Trophée Doré"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25vert0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 198, true),
					new Effect(TypeEffect.DefM, false, 187, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines de Poussière"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 182, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Sombres Mitaines"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 177, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Ranger"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60evo0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 182, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines Silencieuses"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.ASSASSIN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 177, true),
					new Effect(TypeEffect.DefM, false, 168, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Bracelets Ombre de Lune"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 156, true),
					new Effect(TypeEffect.DefM, false, 147, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines de la Nuit Etoilée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 156, true),
					new Effect(TypeEffect.DefM, false, 147, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines de Licorne"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 132, true),
					new Effect(TypeEffect.DefM, false, 125, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines du Voleur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 132, true),
					new Effect(TypeEffect.DefM, false, 125, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Bracelet de la Concentration"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				15, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 113, true),
					new Effect(TypeEffect.DefM, false, 107, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Légers"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.RANGER, GradeName.ASSASSIN, },
				9, ArmorType.GANT, LoaderGauntlet.ICONPATH + "8vert2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 92, true),
					new Effect(TypeEffect.DefM, false, 87, true),
				}),
		};
	}
	
	private static CustomArmor[] getPretre() {
		return new CustomArmor[] {
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Cri du Faucon"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 352, true),
					new Effect(TypeEffect.DefM, false, 263, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCM, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Suprématie"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 345, true),
					new Effect(TypeEffect.DefM, false, 268, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Sage de Verre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 352, true),
					new Effect(TypeEffect.DefM, false, 263, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCM, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Dompteur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 345, true),
					new Effect(TypeEffect.DefM, false, 268, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCP, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Croissant d'Argent"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 340, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCM, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Pays des Merveilles"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 334, true),
					new Effect(TypeEffect.DefM, false, 259, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Lune Pure"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 340, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCM, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Rêve Arc-en-Ciel"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 334, true),
					new Effect(TypeEffect.DefM, false, 259, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCP, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Soie Orientale"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon8", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 334, true),
					new Effect(TypeEffect.DefM, false, 249, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.TCCM, false, 1.6),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Quatre Saisons"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "90blanc5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 327, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.DCCP, false, 11),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Sage Solaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "81sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 331, true),
					new Effect(TypeEffect.DefM, false, 247, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Joueur de Flûte"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 325, true),
					new Effect(TypeEffect.DefM, false, 253, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Lueur de l'Aube"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon8", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 322, true),
					new Effect(TypeEffect.DefM, false, 240, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.TCCM, false, 1.4),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Empire de l'Esprit"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "90blanc5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 316, true),
					new Effect(TypeEffect.DefM, false, 245, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.DCCP, false, 9),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Idylle Aérienne"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 320, true),
					new Effect(TypeEffect.DefM, false, 239, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Astronome Fou"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 314, true),
					new Effect(TypeEffect.DefM, false, 244, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Dévotion Spirituelle"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 310, true),
					new Effect(TypeEffect.DefM, false, 232, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.TCCM, false, 1.2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Mauvais Augure"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 304, true),
					new Effect(TypeEffect.DefM, false, 237, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.DCCP, false, 7),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Serviteur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 308, true),
					new Effect(TypeEffect.DefM, false, 230, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Oracle de l'Ombre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 302, true),
					new Effect(TypeEffect.DefM, false, 235, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Psaume Oraculaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon9", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 299, true),
					new Effect(TypeEffect.DefM, false, 224, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCM, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Châtiment Céleste"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon10", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 293, true),
					new Effect(TypeEffect.DefM, false, 228, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Souffle Charmeur"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon9", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 296, true),
					new Effect(TypeEffect.DefM, false, 222, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Mystère Céleste"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon10", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 290, true),
					new Effect(TypeEffect.DefM, false, 226, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Brassards Liturgiques"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 287, true),
					new Effect(TypeEffect.DefM, false, 214, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCM, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Chamane"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 281, true),
					new Effect(TypeEffect.DefM, false, 218, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCP, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Fins de Cyan"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 284, true),
					new Effect(TypeEffect.DefM, false, 212, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Lin Épais"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 278, true),
					new Effect(TypeEffect.DefM, false, 216, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Pardon"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 274, true),
					new Effect(TypeEffect.DefM, false, 205, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de Lumière Etoilée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 269, true),
					new Effect(TypeEffect.DefM, false, 209, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Disciple de Platine"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "25pvp1", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 271, true),
					new Effect(TypeEffect.DefM, false, 203, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Ville Dorée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 266, true),
					new Effect(TypeEffect.DefM, false, 207, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Route Divine"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 263, true),
					new Effect(TypeEffect.DefM, false, 199, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Ecaille de Dragon"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 256, true),
					new Effect(TypeEffect.DefM, false, 205, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Jugement"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 245, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Grand Chef"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 238, true),
					new Effect(TypeEffect.DefM, false, 190, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de l'Oeil du Jugement"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 245, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Langage de la Forêt"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 238, true),
					new Effect(TypeEffect.DefM, false, 190, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Sceau Sacré"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 234, true),
					new Effect(TypeEffect.DefM, false, 169, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Sprite des Arbres"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 217, true),
					new Effect(TypeEffect.DefM, false, 174, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Lumière Sacrée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 234, true),
					new Effect(TypeEffect.DefM, false, 169, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Mélancoliques pour l'Esprit de l'Ancêtre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 217, true),
					new Effect(TypeEffect.DefM, false, 174, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Loi Eternelle"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 201, true),
					new Effect(TypeEffect.DefM, false, 152, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Prophétie"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 195, true),
					new Effect(TypeEffect.DefM, false, 157, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Monastère"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 201, true),
					new Effect(TypeEffect.DefM, false, 152, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Murmure Silencieux"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SAGE, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 195, true),
					new Effect(TypeEffect.DefM, false, 157, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Evêque"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 176, true),
					new Effect(TypeEffect.DefM, false, 137, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Xianlo"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 176, true),
					new Effect(TypeEffect.DefM, false, 137, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Fête"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 150, true),
					new Effect(TypeEffect.DefM, false, 116, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Bienveillance"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "50pve3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 150, true),
					new Effect(TypeEffect.DefM, false, 116, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Gospel"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				15, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 127, true),
					new Effect(TypeEffect.DefM, false, 100, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Prêtre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.CLERC, GradeName.SAGE, },
				9, ArmorType.GANT, LoaderGauntlet.ICONPATH + "8vert2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 104, true),
					new Effect(TypeEffect.DefM, false, 80, true),
				}),
		};
	}
	
	private static CustomArmor[] getMage() {
		return new CustomArmor[] {
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Spirale Gelée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 282, true),
					new Effect(TypeEffect.DefM, false, 268, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCM, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Croc de Zombie"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80nucleus7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 288, true),
					new Effect(TypeEffect.DefM, false, 263, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCM, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Foudre Apocalyptique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 282, true),
					new Effect(TypeEffect.DefM, false, 268, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.DCCM, false, 15),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Survivant de l'Apocalypse"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				100, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 288, true),
					new Effect(TypeEffect.DefM, false, 263, true),
					new Effect(TypeEffect.ESQ, false, 6),
					new Effect(TypeEffect.TCCM, false, 2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Forge Élémentaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "91sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 273, true),
					new Effect(TypeEffect.DefM, false, 259, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCM, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Fureur Noire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "65pvp7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 278, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCM, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Volute Nuageuse"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "90gold6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 273, true),
					new Effect(TypeEffect.DefM, false, 259, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.DCCM, false, 13),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Brume Noire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				95, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 278, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 5),
					new Effect(TypeEffect.TCCM, false, 1.8),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Codex"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon11", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 268, true),
					new Effect(TypeEffect.DefM, false, 254, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.DCCM, false, 11),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Somnambule"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				90, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon12", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 273, true),
					new Effect(TypeEffect.DefM, false, 249, true),
					new Effect(TypeEffect.ESQ, false, 4),
					new Effect(TypeEffect.TCCM, false, 1.6),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants d'Atlas"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 266, true),
					new Effect(TypeEffect.DefM, false, 253, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Esprits Lyriques"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				89, ArmorType.GANT, LoaderGauntlet.ICONPATH + "80pve7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 271, true),
					new Effect(TypeEffect.DefM, false, 247, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Envies Enfouies"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon11", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 258, true),
					new Effect(TypeEffect.DefM, false, 245, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.DCCM, false, 9),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Dernier des Exorcistes"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				85, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon12", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 263, true),
					new Effect(TypeEffect.DefM, false, 240, true),
					new Effect(TypeEffect.ESQ, false, 3),
					new Effect(TypeEffect.TCCM, false, 1.4),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Toucher de la Déesse"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 257, true),
					new Effect(TypeEffect.DefM, false, 244, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Mal Diabolique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				84, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 262, true),
					new Effect(TypeEffect.DefM, false, 239, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Invisible Fissure"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "88bleu6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 249, true),
					new Effect(TypeEffect.DefM, false, 237, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.DCCM, false, 7),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Propagation de la Mort"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				80, ArmorType.GANT, LoaderGauntlet.ICONPATH + "86bleu7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 254, true),
					new Effect(TypeEffect.DefM, false, 232, true),
					new Effect(TypeEffect.ESQ, false, 2),
					new Effect(TypeEffect.TCCM, false, 1.2),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Éléments Déchaînés"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "95pve6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 247, true),
					new Effect(TypeEffect.DefM, false, 235, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Cristal Sombre"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				79, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 252, true),
					new Effect(TypeEffect.DefM, false, 230, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de l'Osmose Cosmique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon13", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 239, true),
					new Effect(TypeEffect.DefM, false, 228, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCM, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants des Ténèbres"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				75, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon14", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 244, true),
					new Effect(TypeEffect.DefM, false, 224, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCM, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets d'Inspiration Magique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon13", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 237, true),
					new Effect(TypeEffect.DefM, false, 226, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Tuerie Infernale"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				74, ArmorType.GANT, LoaderGauntlet.ICONPATH + "icon14", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 242, true),
					new Effect(TypeEffect.DefM, false, 222, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Mitaines de Mauvais Goût"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "95pve6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 230, true),
					new Effect(TypeEffect.DefM, false, 218, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.DCCM, false, 5),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Fins du Doux Péché"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				70, ArmorType.GANT, LoaderGauntlet.ICONPATH + "75evo7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 235, true),
					new Effect(TypeEffect.DefM, false, 214, true),
					new Effect(TypeEffect.ESQ, false, 1),
					new Effect(TypeEffect.TCCM, false, 1),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Cuir Léger"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70lingot6", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 228, true),
					new Effect(TypeEffect.DefM, false, 216, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets de Peau"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				69, ArmorType.GANT, LoaderGauntlet.ICONPATH + "70nucleus7", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 233, true),
					new Effect(TypeEffect.DefM, false, 212, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Promeneur Temporel"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 220, true),
					new Effect(TypeEffect.DefM, false, 209, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Magicien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				65, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 225, true),
					new Effect(TypeEffect.DefM, false, 205, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-mains de la Limite Élémentaire"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "40pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 218, true),
					new Effect(TypeEffect.DefM, false, 207, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Protège-Mains du Roi des Ténèbres"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				64, ArmorType.GANT, LoaderGauntlet.ICONPATH + "60pve5", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 222, true),
					new Effect(TypeEffect.DefM, false, 203, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets des Abysses"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 216, true),
					new Effect(TypeEffect.DefM, false, 199, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Cosmiques"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				60, ArmorType.GANT, LoaderGauntlet.ICONPATH + "91sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 210, true),
					new Effect(TypeEffect.DefM, false, 205, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Chaos"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 201, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Vide"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 195, true),
					new Effect(TypeEffect.DefM, false, 190, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Drapés de l'Os Magique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 201, true),
					new Effect(TypeEffect.DefM, false, 185, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets Originels"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				53, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 195, true),
					new Effect(TypeEffect.DefM, false, 190, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Fantôme"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 183, true),
					new Effect(TypeEffect.DefM, false, 169, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Grand Guide Magique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 178, true),
					new Effect(TypeEffect.DefM, false, 174, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gantelets du Monstre Diabolique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "53vert3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 183, true),
					new Effect(TypeEffect.DefM, false, 169, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Puissants Gantelets de la Sorcière"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				45, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 178, true),
					new Effect(TypeEffect.DefM, false, 174, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de Convocation"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "8vert2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 164, true),
					new Effect(TypeEffect.DefM, false, 152, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Bariolés"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 159, true),
					new Effect(TypeEffect.DefM, false, 156, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Accord"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.NECROMANCIEN, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "8vert2", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 164, true),
					new Effect(TypeEffect.DefM, false, 152, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Magnifiques Gantelets"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, },
				37, ArmorType.GANT, LoaderGauntlet.ICONPATH + "100pve0", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 159, true),
					new Effect(TypeEffect.DefM, false, 156, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de la Fée"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 140, true),
					new Effect(TypeEffect.DefM, false, 137, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Vent Fantastique"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				29, ArmorType.GANT, LoaderGauntlet.ICONPATH + "37bleu3", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 140, true),
					new Effect(TypeEffect.DefM, false, 137, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants du Magicien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 119, true),
					new Effect(TypeEffect.DefM, false, 116, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Astrologue"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				21, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 119, true),
					new Effect(TypeEffect.DefM, false, 116, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants Élémentaires"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				15, ArmorType.GANT, LoaderGauntlet.ICONPATH + "96sprite4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 102, true),
					new Effect(TypeEffect.DefM, false, 100, true),
				}),
			new CustomArmor(new HashMap<Language, String>() {{ put(Language.FR, "Gants de l'Apprenti Magicien"); put(Language.EN, ""); }},
				new GradeName[] { GradeName.SORCIER, GradeName.NECROMANCIEN, },
				9, ArmorType.GANT, LoaderGauntlet.ICONPATH + "30pve4", new Calculable[] {
					new Effect(TypeEffect.DefP, false, 82, true),
					new Effect(TypeEffect.DefM, false, 80, true),
				}),
		};
	}
	
	private static CustomArmor[] getMeca() {
		return new CustomArmor[] {
			
		};
	}
	
	private static CustomArmor[] getVoyageur() {
		return new CustomArmor[] {
			
		};
	}
}