package fr.vlik.grandfantasia.loader;

import fr.vlik.grandfantasia.enums.TypeEffect;
import fr.vlik.grandfantasia.equip.Ride;
import fr.vlik.grandfantasia.stats.Effect;

public class LoaderRide {

	static Ride[] getRide() {
		return new Ride[] {
			new Ride("Mordragon spectral de guerre", 1, true, "reinca", new Effect(TypeEffect.Depla, false, 50)),
			new Ride("Goldo-Lion de Guerre", 60, false, "goldo3", new Effect(TypeEffect.Depla, false, 60)),
			new Ride("Loup Spectral de Combat", 60, false, "loup0", new Effect(TypeEffect.Depla, false, 60)),
			
			new Ride("Aérowing de combat", 40, false, "airwing1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Alpaga Étincelant de combat", 40, false, "alpaga", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Chat malin à cloche noire de combat", 40, false, "chat2", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Cheval de Guerre des Flammes Sombres", 40, false, "cheval0", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Couple de renards rose printemps de combat", 40, false, "renard3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dents-de-sabre de Glace Suprême", 40, false, "tigre7", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dents-de-sabre Enragé Suprême", 40, false, "tigre8", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dents-de-sabre Féroce Suprême", 40, false, "tigre6", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon améthyste de combat", 40, false, "dragon6", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon ardent de combat", 40, false, "dragon9", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon des ombres", 40, false, "dragon10", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon doré impérial", 40, false, "dragon11", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon infernal", 40, false, "dragon7", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon mécanique de combat", 40, false, "meca0", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon prestigieux", 40, false, "dragon8", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Dragon ténébreux de combat", 40, false, "dragon3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Écureuil de Guerre", 40, false, "ecureuil", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Étalon enflammé de combat", 40, false, "cheval4", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Félin flamboyant de combat", 40, false, "chat1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Fenrir enragé de combat", 40, false, "renard5", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Fléau de l'ombre", 40, false, "tigre9", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Goldo-Lion de Guerre", 40, false, "goldo3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Kurama à Neuf Queues de Bataille", 40, false, "kurama", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Licorne Cosmique de combat", 40, false, "cheval1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Lion cramoisi de combat", 40, false, "lion2", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Loup de Combat de la Flamme mystique", 40, false, "loup6", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Loup de Combat de la Flamme opaline", 40, false, "loup5", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Loup des ténèbres", 40, false, "loup3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture de Combat : Artillerie Mobile Baroque", 40, false, "canon", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture de Combat : Scorpions Jumeaux de Bataille", 40, false, "scorpion3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture de combat de Sprite précurseur", 40, false, "tank1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture de Combat Lion Céleste", 40, false, "lion0", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture de Combat Otto des Abîmes", 40, false, "loup7", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture épique du GM Garuda", 40, false, "GFWT", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture Loup Lotus rouge", 40, false, "loup4", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Monture volante de combat de Ronin", 40, false, "volant", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Renard bleu ultime de combat", 40, false, "renard1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Renard noir ultime rapide de combat", 40, false, "renard4", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Renard rouge ultime de combat", 40, false, "renard0", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Renne du Père Noël féroce", 40, false, "renne", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Rosa l'hélicoptère de combat", 40, false, "helico2", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Scorpion de combat de cristal pourpre à double place", 40, false, "scorpion1", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Vilain pingouin de combat", 40, false, "manchot3", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Voiture de sport « Pluie de météores » de combat", 40, false, "voiture2", new Effect(TypeEffect.Depla, false, 100)),
			new Ride("Voiture rapide de combat", 40, false, "voiture0", new Effect(TypeEffect.Depla, false, 100)),
			
			new Ride("Dragon de combat en armure", 40, false, "dragon4", new Effect(TypeEffect.Depla, false, 95)),
			
			new Ride("Dragon de combat blindé", 40, false, "dragon5", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Élégante Alice spectrale de combat", 40, false, "yggdra1", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Goldo-Tigre rapide de Combat", 40, false, "tigre1", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Monture Ronto de combat digne", 40, false, "yggdra2", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Renard bleu ultime rapide de combat", 40, false, "renard1", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Renard rouge ultime rapide de combat", 40, false, "renard0", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Tigre des Glaces Rapide de Combat", 40, false, "tigre3", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Tigre des Ombres Rapide de Combat", 40, false, "tigre5", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Tigre Rouge rapide de Combat", 40, false, "tigre2", new Effect(TypeEffect.Depla, false, 90)),
			new Ride("Tigre Vert Rapide de Combat", 40, false, "tigre4", new Effect(TypeEffect.Depla, false, 90)),
			
			new Ride("Lapin Sauteur de Combat", 40, false, "lapin", new Effect(TypeEffect.Depla, false, 85)),
			new Ride("Lion de Guerre d'Onyx", 40, false, "goldo1", new Effect(TypeEffect.Depla, false, 85)),
			new Ride("Manchot Dodu de Combat Rapide", 40, false, "manchot0", new Effect(TypeEffect.Depla, false, 85)),
			new Ride("Puissant Loup de Combat", 40, false, "loup1", new Effect(TypeEffect.Depla, false, 85)),
			
			new Ride("Dragon violet de combat", 40, false, "dragon12", new Effect(TypeEffect.Depla, false, 80)),
			new Ride("Loup Sanglant de Combat", 40, false, "loup1", new Effect(TypeEffect.Depla, false, 80)),
			
			new Ride("Airwing de combat", 40, false, "airwing0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Caddie de combat pour Sprite", 40, false, "caddie", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Dragon mécanique enflammé de combat", 40, false, "meca1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Dragon Noir de Combat", 40, false, "dragon1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Étalon d'argent démoniaque", 40, false, "cheval3", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Étalon de guerre de Morgoth", 40, false, "cheval5", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Étalon doré de combat", 40, false, "cheval2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Fantôme d'Hattori", 40, false, "chevalier", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Félin de l'Aria Nocturne", 40, false, "chat0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Fléau de l'ombre la panthère", 40, false, "tigre10", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Goldo-Tigre de Combat", 40, false, "tigre1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Hélicoptère à vapeur blindé", 40, false, "helico0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Hélicoptère solaire de combat", 40, false, "helico1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Jeune Dragon de Combat", 40, false, "dragon0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Lapin Sauteur de Combat", 40, false, "lapin", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Lion ailé de combat", 40, false, "lion1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Lion de Guerre Noir", 40, false, "goldo1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Lion Doré de Combat", 40, false, "goldo0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Lion Violet de Combat", 40, false, "goldo2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Maître des poulpes de combat", 40, false, "poulpe", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Manchot Dodu de Combat", 40, false, "manchot0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Manchot jaune de combat", 40, false, "manchot2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Manchot Soldat du Cœur", 40, false, "manchot1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Méca-monture de combat Noirflamme", 40, false, "robot1", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Monture de combat de Sprite pionnier", 40, false, "tank0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Monture de combat scorpion mécanique", 40, false, "scorpion0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Ours Polaire de combat", 40, false, "ours", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Pyrodragon démoniaque de combat", 40, false, "dragon2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Renard des Ténèbres de combat", 40, false, "renard2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Robot Tueur de Combat", 40, false, "tigre0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Scorpion de combat nocturne deux places", 40, false, "scorpion2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Sprite d'azur de combat", 40, false, "tank3", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Sprite Gundam Volant", 40, false, "robot0", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Tank Sprite de combat", 40, false, "tank2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Tigre des Glaces de Combat", 40, false, "tigre3", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Tigre des Ombres de Combat", 40, false, "tigre5", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Tigre Rouge de Combat", 40, false, "tigre2", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Tigre Vert de Combat", 40, false, "tigre4", new Effect(TypeEffect.Depla, false, 75)),
			new Ride("Voiture de sport de l'Ombre écarlate", 40, false, "voiture1", new Effect(TypeEffect.Depla, false, 75)),
			
			new Ride("Armure Mécanique en Alliage Supérieur Élite", 20, false, "armure", new Effect(TypeEffect.Depla, false, 40)),
			new Ride("Chocobo Ouragan Suprême", 20, false, "chocobo", new Effect(TypeEffect.Depla, false, 40)),
			new Ride("Loup Rapide Élite", 20, false, "loup2", new Effect(TypeEffect.Depla, false, 40)),
		};
	}
	
}
